### ISSUE TITLE
Box for easy clipboard copying

### ISSUE THREAD

**Issue by mudler** [Sabayon/community-website#7]
It would be nice to have a button in the modal box that copies the link about the package displayed straight into the clipboard, making it more easy to share.

**Comment by Ryuno-Ki** [comment]
In #7 I implemented a solution, which needs some testing on mobile.

According to [Can I Use](http://caniuse.com/#search=execcommand) I'm pretty sure, it will work.
Otherwise we could make use of [clipboard.js](https://clipboardjs.com/).

My main concern is about discoverability and UX.

**Comment by mudler** [comment]
I've tried it, but it seems to me that copies the package name instead of the url

**Comment by Ryuno-Ki** [comment]
Ah, yeah. My bad. Will fix it this evening!
